export const sections = [
  {
    title: "Popular amenities",
    links: [
      { label: "Cottage with waterfront", path: "/" },
      { label: "Rustic chalets", path: "/" },
      { label: "Cottages with spa", path: "/" },
      { label: "Mini-chalets for rent", path: "/" },
      { label: "Cottage with dogs allowed", path: "/" },
    ],
  },
  {
    title: "Most popular regions",
    links: [
      { label: "Cottage for rent Laurentides", path: "/" },
      { label: "Cottage for rent Quebec", path: "/" },
      { label: "Cottage for rent Lanaudière", path: "/" },
      { label: "Cottage for rent Estrie", path: "/" },
      { label: "Cottage for rent Outaouais", path: "/" },
      { label: "Cottage for rent Charlevoix", path: "/" },
      { label: "Cottage for rent Lac Sain-Jean", path: "/" },
      { label: "Cottage for rent Gaspésie", path: "/" },
      { label: "Cottage for rent Bas Saint-Laurent", path: "/" },
      { label: "Cottage for rent Mauricie", path: "/" },
      { label: "Cottage for rent Stoneham", path: "/" },
      { label: "Cottage for rent Saguenay", path: "/" },
    ],
  },
  {
    title: "COTTAGES NEAR MOUNTAINS",
    links: [
      { label: "Massif de Charlevoix", path: "/" },
      { label: "Massif du Sud", path: "/" },
      { label: "Mont Sainte-Anne", path: "/" },
      { label: "Mont-Tremblant", path: "/" },
      { label: "Bromont", path: "/" },
      { label: "Mont Orford", path: "/" },
      { label: "Owl’s Head", path: "/" },
      { label: "Mont Sutton", path: "/" },
      { label: "Saint-Sauveur", path: "/" },
      { label: "Mont-Grand-Fonds", path: "/" },
    ],
  },
  {
    title: "COTTAGES NEAR LAKES",
    links: [
      { label: "Lac Saint-Jean", path: "/" },
      { label: "Lac à la truite", path: "/" },
      { label: "Lac Aylmer", path: "/" },
      { label: "Lac Simon", path: "/" },
      { label: "Lac Taureau", path: "/" },
      { label: "Lac Mégantic", path: "/" },
      { label: "Lac Brome", path: "/" },
      { label: "Lac Saint-François", path: "/" },
      { label: "Lac Etchemin", path: "/" },
      { label: "Lac Sept-Îles", path: "/" },
    ],
  },
];
